# Generated by Django 5.2.1 on 2025-06-21 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('cod_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('cod_correo', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('enviado', models.BooleanField(default=False, verbose_name='enviado')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('cod_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_pro', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('tamano', models.CharField(choices=[('S', 'Extra Pequeño'), ('M', 'Pequeño'), ('L', 'Mediano'), ('XL', 'Grande')], max_length=2, verbose_name='tamaño')),
                ('capacidad', models.IntegerField(help_text='Cantidad de donas por bolsa', verbose_name='capacidad')),
                ('prec_pro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=50, verbose_name='nombre')),
                ('telefono_proveedor', models.CharField(max_length=13, verbose_name='teléfono')),
                ('direccion_proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección')),
                ('email_proveedor', models.EmailField(blank=True, max_length=50, null=True, verbose_name='correo')),
                ('novedad_proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='novedades')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nom_usua', models.CharField(max_length=15, verbose_name='nombre')),
                ('apell_usua', models.CharField(max_length=20, verbose_name='apellido')),
                ('tele_usua', models.CharField(max_length=15, verbose_name='teléfono')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('DOMI', 'Domiciliario')], default='CLIENTE', max_length=7, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cod_admin', models.AutoField(primary_key=True, serialize=False)),
                ('estado_admin', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8, verbose_name='estado')),
                ('cod_usua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('direc_cliente', models.CharField(max_length=50, verbose_name='dirección')),
                ('historial_compras', models.IntegerField(default=0, verbose_name='compras realizadas')),
                ('cod_usua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('cod_domi', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='disponible')),
                ('cod_usua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domiciliario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domiciliario',
                'verbose_name_plural': 'Domiciliarios',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('cod_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_insumo', models.CharField(max_length=50, verbose_name='nombre')),
                ('cnt_insumo', models.IntegerField(default=0, verbose_name='cantidad')),
                ('unidad_medida', models.CharField(max_length=10, verbose_name='unidad de medida')),
                ('cod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='sdnts.categoriainsumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Glaseado',
            fields=[
                ('cod_glaseado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('Oscuro', 'Oscuro'), ('Blanco', 'Blanco'), ('Colorido', 'Colorido')], max_length=10, verbose_name='tipo')),
                ('color', models.CharField(blank=True, choices=[('Rosado', 'Rosado'), ('Morado', 'Morado'), ('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Verde', 'Verde')], max_length=10, null=True, verbose_name='color')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glaseados', to='sdnts.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('cod_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de entrega')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='sdnts.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('masa_seleccionada', models.CharField(blank=True, max_length=50, null=True)),
                ('cobertura_seleccionada', models.CharField(blank=True, max_length=50, null=True)),
                ('topping_seleccionado', models.CharField(blank=True, max_length=50, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sdnts.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('cod_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('cnt_entrada', models.IntegerField(verbose_name='cantidad')),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('fecha_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='fecha de entrada')),
                ('fecha_caducidad', models.DateField(verbose_name='fecha de caducidad')),
                ('cod_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='sdnts.insumo')),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='sdnts.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de Insumo',
                'verbose_name_plural': 'Entradas de Insumos',
            },
        ),
        migrations.CreateModel(
            name='SaborMasa',
            fields=[
                ('cod_sabor_masa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabores_masa', to='sdnts.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('cod_salida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('fecha_hora_salida', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('cod_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='sdnts.insumo')),
                ('cod_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='sdnts.produccion')),
            ],
            options={
                'verbose_name': 'Salida de Insumo',
                'verbose_name_plural': 'Salidas de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('cod_topping', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripción')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='sdnts.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('cod_combinacion', models.AutoField(primary_key=True, serialize=False)),
                ('cod_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='sdnts.detalleventa')),
                ('cod_glaseado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_primarias', to='sdnts.glaseado')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_personalizadas', to='sdnts.producto')),
                ('cod_sabor_masa_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_primarias', to='sdnts.sabormasa')),
                ('cod_topping_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinaciones_primarias', to='sdnts.topping')),
            ],
            options={
                'verbose_name': 'Combinación de Producto',
                'verbose_name_plural': 'Combinaciones de Productos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En preparación'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=11, verbose_name='estado')),
                ('direccion_entrega', models.CharField(max_length=100, verbose_name='dirección de entrega')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='sdnts.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='cod_venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='sdnts.venta'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('cod_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=9, verbose_name='método de pago')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto total')),
                ('fecha_hora_pago', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=9, verbose_name='estado')),
                ('transaccion_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de transacción')),
                ('cod_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='sdnts.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('cod_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de asignación')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='fecha de salida')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('tarifa_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tarifa de envío')),
                ('segunda_fecha', models.DateTimeField(blank=True, null=True, verbose_name='segunda fecha tentativa')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('firma_recepcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='firma de recepción')),
                ('cod_domi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='sdnts.domiciliario')),
                ('cod_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='sdnts.venta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cod_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sdnts.venta'),
        ),
        migrations.CreateModel(
            name='RecetaPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MASA', 'Masa'), ('GLASEADO', 'Glaseado'), ('TOPPING', 'Topping')], max_length=10)),
                ('unidad_medida', models.CharField(default='g', max_length=10)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_personalizadas', to='sdnts.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.insumo')),
            ],
            options={
                'unique_together': {('cod_producto', 'tipo', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad necesaria')),
                ('unidad_medida', models.CharField(max_length=10)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='sdnts.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.insumo')),
            ],
            options={
                'unique_together': {('cod_producto', 'insumo')},
            },
        ),
    ]
