# Generated by Django 5.2.2 on 2025-06-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='sdnts.venta'),
        ),
    ]
