# Generated by Django 5.2.1 on 2025-06-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('cod_correo', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('enviado', models.BooleanField(default=False, verbose_name='enviado')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('DOMI', 'Domiciliario')], default='CLIENTE', max_length=7, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('masa_seleccionada', models.CharField(blank=True, max_length=50, null=True)),
                ('cobertura_seleccionada', models.CharField(blank=True, max_length=50, null=True)),
                ('topping_seleccionado', models.CharField(blank=True, max_length=50, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sdnts.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.producto')),
            ],
        ),
    ]
