# Generated by Django 5.2.2 on 2025-06-24 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0002_combinacionproducto_cod_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de vencimiento'),
        ),
    ]
