# Generated by Django 5.2.2 on 2025-06-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0003_insumo_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_vencimiento',
        ),
    ]
