# Generated by Django 5.2.2 on 2025-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0003_alter_usuario_managers_remove_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correo',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Correo', 'verbose_name_plural': 'Correos'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='estado_admin',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='glaseado',
            name='color',
            field=models.CharField(blank=True, choices=[('ROSADO', 'Rosado'), ('MORADO', 'Morado'), ('NARANJA', 'Naranja'), ('AZUL', 'Azul'), ('VERDE', 'Verde')], max_length=10, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='glaseado',
            name='tipo',
            field=models.CharField(choices=[('OSCURO', 'Oscuro'), ('BLANCO', 'Blanco'), ('COLORIDO', 'Colorido')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=9, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administradores',
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='carritos',
        ),
        migrations.AlterModelTable(
            name='carritoitem',
            table='carrito_items',
        ),
        migrations.AlterModelTable(
            name='categoriainsumo',
            table='categorias_insumo',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='combinacionproducto',
            table='combinaciones_producto',
        ),
        migrations.AlterModelTable(
            name='correo',
            table='correos',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalles_venta',
        ),
        migrations.AlterModelTable(
            name='domiciliario',
            table='domiciliarios',
        ),
        migrations.AlterModelTable(
            name='entrada',
            table='entradas_insumo',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='envios',
        ),
        migrations.AlterModelTable(
            name='glaseado',
            table='glaseados',
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='insumos',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pagos',
        ),
        migrations.AlterModelTable(
            name='produccion',
            table='producciones',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
        migrations.AlterModelTable(
            name='sabormasa',
            table='sabores_masa',
        ),
        migrations.AlterModelTable(
            name='salida',
            table='salidas_insumo',
        ),
        migrations.AlterModelTable(
            name='topping',
            table='toppings',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas',
        ),
    ]
