# Generated by Django 5.2.2 on 2025-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0004_remove_insumo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=10),
        ),
    ]
