# Generated by Django 5.2.2 on 2025-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0004_alter_correo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correo',
            options={'verbose_name': 'Correo', 'verbose_name_plural': 'Correos'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='estado_admin',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='glaseado',
            name='color',
            field=models.CharField(blank=True, choices=[('Rosado', 'Rosado'), ('Morado', 'Morado'), ('Naranja', 'Naranja'), ('Azul', 'Azul'), ('Verde', 'Verde')], max_length=10, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='glaseado',
            name='tipo',
            field=models.CharField(choices=[('Oscuro', 'Oscuro'), ('Blanco', 'Blanco'), ('Colorido', 'Colorido')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=9, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carrito',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carritoitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoriainsumo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='combinacionproducto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='correo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='domiciliario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entrada',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='glaseado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insumo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pago',
            table=None,
        ),
        migrations.AlterModelTable(
            name='produccion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sabormasa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salida',
            table=None,
        ),
        migrations.AlterModelTable(
            name='topping',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
