# Generated by Django 5.2.2 on 2025-06-11 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0006_remove_combinacionproducto_cod_glaseado_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de entrega'),
        ),
    ]
