# Generated by Django 5.2.2 on 2025-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0008_detalleventa_cobertura_detalleventa_masa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='masa',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='topping',
        ),
    ]
