# Generated by Django 5.2.1 on 2025-06-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0009_remove_detalleventa_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_glaseado_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_secundarias', to='sdnts.glaseado'),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_sabor_masa_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_secundarias', to='sdnts.sabormasa'),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_topping_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinaciones_secundarias', to='sdnts.topping'),
        ),
    ]
