# Generated by Django 5.2.2 on 2025-06-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0010_combinacionproducto_cod_glaseado_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='cod_glaseado_2',
        ),
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='cod_sabor_masa_2',
        ),
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='cod_topping_2',
        ),
    ]
