# Generated by Django 5.2.1 on 2025-06-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0011_remove_combinacionproducto_cod_glaseado_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='nom_entrada',
        ),
    ]
