# Generated by Django 5.2.1 on 2025-06-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0013_remove_entrada_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad del insumo requerida para producir este producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='sdnts.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='sdnts.producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
