# Generated by Django 5.2.1 on 2025-06-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0014_recetaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetaproducto',
            options={},
        ),
        migrations.RenameField(
            model_name='recetaproducto',
            old_name='producto',
            new_name='cod_producto',
        ),
        migrations.AlterUniqueTogether(
            name='recetaproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recetaproducto',
            name='unidad_medida',
            field=models.CharField(default='g', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recetaproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad necesaria'),
        ),
        migrations.AlterField(
            model_name='recetaproducto',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.insumo'),
        ),
        migrations.AlterUniqueTogether(
            name='recetaproducto',
            unique_together={('cod_producto', 'insumo')},
        ),
    ]
