# Generated by Django 5.2.1 on 2025-06-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0015_alter_recetaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='sdnts.detalleventa'),
        ),
    ]
