# Generated by Django 5.2.1 on 2025-06-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0016_combinacionproducto_cod_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glaseado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sabormasa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.AddField(
            model_name='glaseado',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glaseados', to='sdnts.insumo'),
        ),
        migrations.AddField(
            model_name='sabormasa',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabores_masa', to='sdnts.insumo'),
        ),
        migrations.AddField(
            model_name='topping',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='sdnts.insumo'),
        ),
    ]
