# Generated by Django 5.2.1 on 2025-06-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0018_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('S', 'Extra Pequeño'), ('M', 'Pequeño'), ('L', 'Mediano'), ('XL', 'Grande')], max_length=2, verbose_name='tamaño'),
        ),
    ]
