# Generated by Django 5.2.1 on 2025-06-18 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0019_alter_producto_tamano'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MASA', 'Masa'), ('GLASEADO', 'Glaseado'), ('TOPPING', 'Topping')], max_length=10)),
                ('unidad_medida', models.CharField(default='g', max_length=10)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_personalizadas', to='sdnts.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnts.insumo')),
            ],
            options={
                'unique_together': {('cod_producto', 'tipo', 'insumo')},
            },
        ),
    ]
