# Generated by Django 5.2.1 on 2025-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0020_recetapersonalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='segunda_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='segunda fecha tentativa'),
        ),
    ]
