# Generated by Django 5.2.1 on 2025-06-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0021_envio_segunda_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='combinacionproducto',
            name='cod_venta',
        ),
        migrations.AlterField(
            model_name='combinacionproducto',
            name='cod_detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='sdnts.detalleventa'),
            preserve_default=False,
        ),
    ]
