# Generated by Django 5.2.1 on 2025-06-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0022_remove_combinacionproducto_cod_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacionproducto',
            name='cod_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_personalizadas', to='sdnts.producto'),
        ),
    ]
