# Generated by Django 5.2.1 on 2025-06-21 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnts', '0023_combinacionproducto_cod_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacionproducto',
            name='cod_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_personalizadas', to='sdnts.producto'),
        ),
    ]
